# 2: Variabili e Strutture Dati di Base

In questa lezione impareremo come Python tratta le variabili e le principali strutture dati di base: stringhe, liste, tuple, set, dizionari e array (con numpy).  
Alla fine della lezione ci saranno alcuni esercizi per mettere in pratica quanto appreso.

---

## 2.1 Variabili e Assegnazione

Una **variabile** è un contenitore che permette di memorizzare dati.  
In Python, non è necessario dichiarare il tipo: il tipo è determinato al momento dell'assegnazione.

Esempi:

In [2]:
a = 10
b = 3.14
c = True
d = "Ciao, mondo!"

print(type(a), a)
print(type(b), b)
print(type(c), c)
print(type(d), d)

<class 'int'> 10
<class 'float'> 3.14
<class 'bool'> True
<class 'str'> Ciao, mondo!


### Alcune regole per il naming delle variabili:

- Devono iniziare con lettera o underscore _

- Possono contenere lettere, cifre e underscore

- Attenzione alle maiuscole/minuscole: Var ≠ var

## 2.2 Stringhe

Le stringhe sono sequenze immutabili di caratteri, il che significa che una volta create, non possono essere modificate direttamente. Se si tenta di cambiare un carattere di una stringa esistente, si otterrà un errore, ma è possibile creare una nuova stringa che sia una versione modificata di quella originale.

Per la creazione si usano  "..." o '...'. Si può accedere ad un elemento della lista. Si possono estrarre solo alcuni caratteri. Si possono concatenare e ripetere

In [3]:
s = "Ingegneria Informatica" # creazione
print(s[0])        # primo carattere
print(s[-1])       # ultimo carattere
print(s[0:10])     # slice
print(s[:10])
print(s[11:])
print(s + " è bella!")
print(s * 2)

I
a
Ingegneria
Ingegneria
Informatica
Ingegneria Informatica è bella!
Ingegneria InformaticaIngegneria Informatica


### Altri comandi utili

In [4]:
print(s.lower())
print(s.upper())
print(s.replace("Informatica", "Computazione"))
print(s.split())   # di default split su spazi
print("-".join(["Python", "è", "utile"]))

ingegneria informatica
INGEGNERIA INFORMATICA
Ingegneria Computazione
['Ingegneria', 'Informatica']
Python-è-utile


## 2.3 Liste

Le liste sono sequenze mutabili: possiamo modificare il contenuto dopo la creazione.

In [6]:
lst = [1, 2, 3, 4.5, "ciao"]
print(lst)
print(lst[0], lst[-1])
print(lst[1:4])

[1, 2, 3, 4.5, 'ciao']
1 ciao
[2, 3, 4.5]


In [7]:
### Modifiche
lst.append("ultimo")
print(lst)
lst.insert(2, "tra 2 e 3")
print(lst)
lst.remove(2)  # rimuove il primo elemento uguale a 2
print(lst)
lst.pop()      # toglie e restituisce l'ultimo elemento
print(lst)
lst[0] = 100
print(lst)

[1, 2, 3, 4.5, 'ciao', 'ultimo']
[1, 2, 'tra 2 e 3', 3, 4.5, 'ciao', 'ultimo']
[1, 'tra 2 e 3', 3, 4.5, 'ciao', 'ultimo']
[1, 'tra 2 e 3', 3, 4.5, 'ciao']
[100, 'tra 2 e 3', 3, 4.5, 'ciao']


## 2.4 Tuple

Le tuple sono come le liste, ma immutabili. Per creare si usano le tonde invece delle  [   ]

In [10]:
t = (1, 2, 3, "a", "b")
print(t)
print(t[2])
# t[0] = 10    # questo dà errore

(1, 2, 3, 'a', 'b')
3


## 2.5 Set

I set sono insiemi non ordinati, non permettono duplicati.

In [11]:
st = {1, 2, 3, 3, 2}
print(st)   # duplicati tolti

st2 = set([2, 3, 4, 5])
print(st2)

# operazioni
print("unione:", st | st2)
print("intersezione:", st & st2)
print("differenza:", st - st2) # restituisce un nuovo set contenente gli elementi presenti nel primo set ma non nel secondo
# restituisce un nuovo set contenente tutti gli elementi che sono presenti in uno dei due set, 
# ma non in entrambi, escludendo quindi gli elementi comuni
print("differenza simmetrica:", st ^ st2) # 

{1, 2, 3}
{2, 3, 4, 5}
unione: {1, 2, 3, 4, 5}
intersezione: {2, 3}
differenza: {1}
differenza simmetrica: {1, 4, 5}


## 2.6 Dizionari

I dizionari sono mappe chiave → valore. 

In [13]:
d = {"nome": "Alice", "età": 23, "corso": "Informatica"}
print(d)
print(d["nome"])
d["età"] = 24
print(d)
d["città"] = "Lugano"
print(d)

{'nome': 'Alice', 'età': 23, 'corso': 'Informatica'}
Alice
{'nome': 'Alice', 'età': 24, 'corso': 'Informatica'}
{'nome': 'Alice', 'età': 24, 'corso': 'Informatica', 'città': 'Lugano'}


### Altri comandi utili

In [14]:
print(d.keys())
print(d.values())
print(d.items())

if "età" in d:
    print("Età è presente")

dict_keys(['nome', 'età', 'corso', 'città'])
dict_values(['Alice', 24, 'Informatica', 'Lugano'])
dict_items([('nome', 'Alice'), ('età', 24), ('corso', 'Informatica'), ('città', 'Lugano')])
Età è presente


## 2.7 Array con NumPy !!!!

Le liste vanno bene per piccoli usi, ma per dati numerici, calcoli vettoriali ecc. è meglio usare gli array di numpy.

In [19]:
import numpy as np

arr = np.array([1.0, 2.0, 3.0, 4.0])
print(arr)
print(arr * 2)
print(arr + arr)
print(arr ** 2)
print(np.sin(arr))

[1. 2. 3. 4.]
[2. 4. 6. 8.]
[2. 4. 6. 8.]
[ 1.  4.  9. 16.]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


### Creazione di matrici

In [22]:
A = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(A)
print(A.shape)
print(A[0, :])
print(A[:, 1])
print(A[1:3, 1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[1 2 3]
[2 5 8]
[[5 6]
 [8 9]]
